# Generated by Django 4.2.15 on 2024-08-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_product_created_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
