# Generated by Django 4.2.15 on 2024-08-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cart_items_remove_cart_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
