# Generated by Django 4.2.15 on 2024-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cart_user_cart_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                default="default_session_key", max_length=40, unique=True
            ),
        ),
    ]
